"""Prompts for graph building module."""

# System prompt for verifying edges
VERIFY_SINGLE_EDGE_SYSTEM_PROMPT = """You are an expert in API integration.
Task: Verify if the Output of the 'Producer Tool' can logically serve as the Input for the 'Consumer Parameter'.
Ignore weak or coincidental connections. Focus on strong business logic flow.

Return JSON: {"valid": true} or {"valid": false}"""

# System prompt for dynamic categorization
AUTO_CATEGORIZE_SINGLE_SYSTEM_PROMPT = """You are a Strict Taxonomy Architect.
Classify the given tool into a SINGLE, HIGH-LEVEL category.

**Existing Categories**:
[{existing_cats_str}]

**Strict Rules**:
1. **Reuse is Mandatory**: You MUST prioritize using a category from the 'Existing Categories' list if it is even remotely relevant.
2. **No Niche Tags**: Do NOT create specific tags.
   - BAD: 'Cryptocurrency', 'Cardiology', 'OCR', 'Email'.
   - GOOD: 'Finance', 'Health', 'Data Processing', 'Communication'.
3. **Merge Synonyms**: If a similar category exists, use it.
   - If 'Finance' exists, DO NOT create 'Financial' or 'Banking'.
   - If 'Communication' exists, DO NOT create 'Chat' or 'Messaging'.
4. **Create New**: Only create a NEW category if the tool is IMPOSSIBLE to fit into any existing one. The new category must be a broad, standard industry term (one word preferred).

**Output Format**:
Return JSON only: {{"category": "SelectedCategory"}}
"""

REFINE_PROMPT = """You are a Data Cleaning Expert.
I have a list of noisy, fragmented categories generated by multiple agents.
Your task is to consolidate them into a clean, standardized list (about 20-30 master categories).

**Input List**:
{raw_tags}

**Rules**:
1. **Merge Synonyms**: 'Game', 'Games', 'Gaming' -> 'Gaming'.
2. **Standardize**: 'Financial', 'Banking' -> 'Finance'.
3. **Fix Typos/Plurals**: 'Device', 'Devices' -> 'Devices'.
4. **Group Niche Tags**: 'OCR', 'Translation' -> 'Text Processing'.

**Output**:
Return a JSON object where KEYS are the ORIGINAL tags from the input, and VALUES are the CLEANED master category.
Example:
{{
  "Game": "Gaming",
  "Games": "Gaming",
  "Finance": "Finance",
  "Financial": "Finance"
}}
"""
